const board=document.getElementById('game');const message=document.getElementById('message');const startBtn=document.getElementById('startBtn');const scoreEl=document.getElementById('score');const timeEl=document.getElementById('time');const levelEl=document.getElementById('level');const soundBtn=document.getElementById('soundBtn');const coinsEl=document.getElementById('coins');const livesEl=document.getElementById('lives');const characterEl=document.getElementById('character');const mapEl=document.getElementById('map');const bestEl=document.getElementById('best');const rewardEl=document.getElementById('reward');const pauseBtn=document.getElementById('pauseBtn');
let state={score:0,coins:0,lives:3,time:30,level:1,map:0,character:0,running:false,paused:false,sound:true,streak:0,power:null,best:Number(localStorage.getItem('tangkapBest')||0),timer:null,spawn:null,star:null};
const maps=[{name:'Langit Ceria',className:'sky'},{name:'Hutan Ajaib',className:'forest'},{name:'Laut Pelangi',className:'ocean'},{name:'Ruang Angkasa',className:'space'}];
const chars=[{emoji:'🧒',name:'Bimo'},{emoji:'👧',name:'Lala'},{emoji:'🐱',name:'Mimi'},{emoji:'🐰',name:'Bunny'}];
const rewards=['🌟 Bintang Emas','🏅 Juara Hebat','🎁 Peti Kejutan','👑 Raja Langit','💎 Kolektor Berlian'];
function audio(freq=600,d=.07){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!window.ctx)window.ctx=new C();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.07,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+d)}catch(e){}}
function save(){localStorage.setItem('tangkapBest',String(state.best));localStorage.setItem('tangkapCoins',String(state.coins));localStorage.setItem('tangkapCharacter',String(state.character));}
function render(){scoreEl.textContent=state.score;timeEl.textContent=state.time;levelEl.textContent=state.level;coinsEl.textContent=state.coins;livesEl.textContent='❤️'.repeat(state.lives)+'♡'.repeat(3-state.lives);bestEl.textContent=state.best;characterEl.textContent=chars[state.character].emoji;mapEl.textContent=maps[state.map].name;rewardEl.textContent=state.score>=20?rewards[Math.min(4,Math.floor(state.score/20))]:'🎯 Kejar 20 poin untuk hadiah!';board.className='game-board '+maps[state.map].className+(state.paused?' paused':'');}
function pos(el){el.style.left=(5+Math.random()*88)+'%';el.style.top=(8+Math.random()*78)+'%';}
function makeItem(type){const b=document.createElement('button');b.className='item '+type;const content=type==='coin'?'🪙':type==='heart'?'💖':type==='clock'?'⏰':type==='magnet'?'🧲':type==='rainbow'?'🌈':['⭐','🌟','✨'][Math.floor(Math.random()*3)];b.textContent=content;b.setAttribute('aria-label',type);pos(b);b.onclick=()=>collect(type);board.appendChild(b);state.star=b;setTimeout(()=>{if(b.isConnected)b.remove()},Math.max(800,1400-state.level*60));}
function collect(type){if(!state.running||state.paused)return;if(state.star){state.star.remove();state.star=null}if(type==='star'){state.score++;state.streak++;state.coins+=state.streak%5===0?3:1;audio(600+state.level*50,.06);if(state.score%5===0){state.level=Math.min(10,1+Math.floor(state.score/5));state.map=Math.floor((state.level-1)/3)%maps.length;flash('LEVEL '+state.level+'! 🎉')}}if(type==='coin'){state.coins+=5;state.streak++;audio(1000,.08);flash('+5 KOIN 🪙')}if(type==='heart'){state.lives=Math.min(3,state.lives+1);audio(800,.1);flash('NYAWA +1 ❤️')}if(type==='clock'){state.time+=7;audio(500,.12);flash('+7 DETIK ⏰')}if(type==='magnet'){state.power='magnet';audio(900,.12);flash('MAGNET AKTIF 🧲')}if(type==='rainbow'){state.power='double';audio(1200,.14);flash('SKOR x2 🌈')}render();save();nextItem();}
function nextItem(){if(!state.running||state.paused)return;let r=Math.random();let type=r<.72?'star':r<.82?'coin':r<.88?'heart':r<.94?'clock':r<.97?'magnet':'rainbow';makeItem(type);clearTimeout(state.spawn);state.spawn=setTimeout(nextItem,Math.max(500,1150-state.level*65));}
function flash(t){const f=document.createElement('div');f.className='flash';f.textContent=t;board.appendChild(f);setTimeout(()=>f.remove(),900)}
function start(){clearInterval(state.timer);clearTimeout(state.spawn);state.score=0;state.lives=3;state.time=30;state.level=1;state.map=0;state.streak=0;state.power=null;state.running=true;state.paused=false;message.classList.add('hidden');render();nextItem();state.timer=setInterval(()=>{if(!state.paused){state.time--;if(state.time%5===0&&state.lives>0&&Math.random()<.25){state.lives--;flash('Aduh! 💔')}render();if(state.time<=0||state.lives<=0)end()}},1000);audio(500,.12)}
function end(){state.running=false;clearInterval(state.timer);clearTimeout(state.spawn);if(state.star)state.star.remove();state.star=null;const newBest=state.score>state.best;if(newBest)state.best=state.score;const key='leaderboard';const lb=JSON.parse(localStorage.getItem(key)||'[]');lb.push({score:state.score,coins:state.coins,date:new Date().toLocaleDateString('id-ID')});lb.sort((a,b)=>b.score-a.score);localStorage.setItem(key,JSON.stringify(lb.slice(0,5)));save();const reward=state.score>=20?rewards[Math.min(4,Math.floor(state.score/20))]:'🎈 Tetap semangat!';message.innerHTML=`<div class="card"><div class="big-star">🏆</div><h2>Permainan Selesai!</h2><p>Skor <strong>${state.score}</strong> · Koin <strong>${state.coins}</strong> · Level <strong>${state.level}</strong></p><div class="reward">${newBest?'🎉 REKOR BARU! ':''}${reward}</div><div class="leader">${leaderboardHTML()}</div><button id="restart" class="primary-btn">Main Lagi</button></div>`;message.classList.remove('hidden');document.getElementById('restart').onclick=start;render();audio(420,.15);setTimeout(()=>audio(700,.16),150)}
function leaderboardHTML(){const lb=JSON.parse(localStorage.getItem('leaderboard')||'[]');if(!lb.length)return '';return '<div class="lb-title">🏆 5 Skor Terbaik</div>'+lb.slice(0,5).map((x,i)=>`<div class="lb-row"><span>${i+1}. ${x.date}</span><strong>${x.score} ⭐</strong></div>`).join('')}
function togglePause(){if(!state.running)return;state.paused=!state.paused;if(state.paused){pauseBtn.textContent='▶️';flash('PAUSE')}else{pauseBtn.textContent='⏸️';nextItem()}render()}
soundBtn.onclick=()=>{state.sound=!state.sound;soundBtn.textContent=state.sound?'🔊':'🔇';if(state.sound)audio()};pauseBtn.onclick=togglePause;startBtn.onclick=start;document.getElementById('charBtn').onclick=()=>{state.character=(state.character+1)%chars.length;render();save();flash(chars[state.character].emoji+' '+chars[state.character].name)};render();